version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: rentadmin_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rentadmin_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rentadmin_backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=super-secret-jwt-key-for-rent-admin-production-2024
      - PIN_CODE=20031997
      - CORS_ORIGIN=http://87.242.103.146
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/production.sqlite3
    volumes:
      - sqlite_data:/app/data
      - ./backend/dev.sqlite3:/app/data/production.sqlite3
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - rentadmin_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:

networks:
  rentadmin_network:
    driver: bridge