services:
  nginx:
    image: nginx:alpine
    container_name: rentadmin_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - rentadmin_network

networks:
  rentadmin_network:
    driver: bridge